name: Register flows on merge dev
on:
  pull_request:
    branches:
      - dev
    types:
      - closed
 
jobs:
  create-matrix:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "::set-output name=matrix::$(find projects/ -maxdepth 2 -mindepth 2 | jq -Rsc '. / "\n" - [""]')"
  register-flows:
    if: github.event.pull_request.merged == true
    env:
      env: dev
    needs: create-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flow-folder: ${{ fromJSON(needs.create-matrix.outputs.matrix) }}
      max-parallel: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: setup python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.x'
      - name: Check python version
        run: echo $(python --version)
      - name: install prefect
        run: pip install prefect
      - name: install dependencies
        working-directory: ${{ matrix.flow-folder }}
        run: pip install -r requirements.txt
      - name: prefect login
        run: prefect auth login -k ${{ secrets.PREFECT_CLOUD_KEY }}
      - name: docker login
        run: docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: register flows
        working-directory: ${{ matrix.flow-folder }}
        run: prefect register --project $(echo "${{ matrix.flow-folder }}" | cut -d '/' -f2) --path ./ 
